-- ============================================================
-- Script  : 05_UPDATE_LABEL_INFO.sql
-- Module  : ICSR
-- Purpose : Populate LABEL_INFO column in TABLE_COLUMN_METADATA
--           with E2B R2 / R3 element tags for all ICSR fields
--           that map to ICH E2B elements.
--           Format: {"r2":"A.1.0.1","r3":"C.1.1"}
-- ============================================================

-- ── Table 500 — ICSR_CASES ────────────────────────────────────
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"A.1.0.1","r3":"C.1.1"}'   WHERE MODULE_ID='ICSR' AND FIELD_ID='500001';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"A.1.0.2","r3":"C.1.2"}'   WHERE MODULE_ID='ICSR' AND FIELD_ID='500002';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"A.1.1","r3":"C.1.3"}'     WHERE MODULE_ID='ICSR' AND FIELD_ID='500003';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"A.1.2","r3":"C.1.4"}'     WHERE MODULE_ID='ICSR' AND FIELD_ID='500004';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"A.1.3","r3":"C.1.5"}'     WHERE MODULE_ID='ICSR' AND FIELD_ID='500005';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"A.1.4","r3":"C.1.6"}'     WHERE MODULE_ID='ICSR' AND FIELD_ID='500006';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"A.1.5","r3":"C.1.7"}'     WHERE MODULE_ID='ICSR' AND FIELD_ID='500007';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"A.1.6","r3":"C.1.8"}'     WHERE MODULE_ID='ICSR' AND FIELD_ID='500008';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"A.1.7","r3":"C.1.3"}'     WHERE MODULE_ID='ICSR' AND FIELD_ID='500011';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"A.1.8","r3":"C.1.9"}'     WHERE MODULE_ID='ICSR' AND FIELD_ID='500012';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"A.1.9","r3":"C.1.10"}'    WHERE MODULE_ID='ICSR' AND FIELD_ID='500013';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"A.1.10","r3":"C.1.11"}'   WHERE MODULE_ID='ICSR' AND FIELD_ID='500014';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"A.1.11","r3":"C.1.12"}'   WHERE MODULE_ID='ICSR' AND FIELD_ID='500015';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"A.1.12","r3":"C.1.13"}'   WHERE MODULE_ID='ICSR' AND FIELD_ID='500016';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"A.2.1","r3":"C.2.r.1"}'   WHERE MODULE_ID='ICSR' AND FIELD_ID='500017';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"A.2.2","r3":"C.2.r.2"}'   WHERE MODULE_ID='ICSR' AND FIELD_ID='500018';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"A.2.3","r3":"C.4.r.1"}'   WHERE MODULE_ID='ICSR' AND FIELD_ID='500019';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"A.3.1","r3":"C.3.1"}'     WHERE MODULE_ID='ICSR' AND FIELD_ID='500020';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"A.3.2","r3":"C.3.2"}'     WHERE MODULE_ID='ICSR' AND FIELD_ID='500021';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"A.3.3","r3":"C.3.3"}'     WHERE MODULE_ID='ICSR' AND FIELD_ID='500022';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"A.3.4","r3":"C.3.4"}'     WHERE MODULE_ID='ICSR' AND FIELD_ID='500023';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"A.3.5","r3":"C.3.5"}'     WHERE MODULE_ID='ICSR' AND FIELD_ID='500024';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"A.3.6","r3":"C.3.6"}'     WHERE MODULE_ID='ICSR' AND FIELD_ID='500025';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"A.3.7","r3":"C.3.7"}'     WHERE MODULE_ID='ICSR' AND FIELD_ID='500026';

-- ── Table 515 — ICSR_REPORTER_INFORMATIONS ────────────────────
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"A.2.1.1","r3":"C.2.r.1.1"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='515001';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"A.2.1.2","r3":"C.2.r.1.2"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='515002';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"A.2.1.3","r3":"C.2.r.1.3"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='515003';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"A.2.1.4","r3":"C.2.r.1.4"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='515004';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"A.2.1.5","r3":"C.2.r.1.5"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='515005';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"A.2.1.6","r3":"C.2.r.2"}'   WHERE MODULE_ID='ICSR' AND FIELD_ID='515006';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"A.2.1.7","r3":"C.2.r.3"}'   WHERE MODULE_ID='ICSR' AND FIELD_ID='515007';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"A.2.1.8","r3":"C.2.r.4"}'   WHERE MODULE_ID='ICSR' AND FIELD_ID='515008';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"A.2.1.9","r3":"C.2.r.5"}'   WHERE MODULE_ID='ICSR' AND FIELD_ID='515009';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"A.2.1.10","r3":"C.2.r.6"}'  WHERE MODULE_ID='ICSR' AND FIELD_ID='515010';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"A.2.1.11","r3":"C.2.r.7"}'  WHERE MODULE_ID='ICSR' AND FIELD_ID='515011';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"A.2.1.12","r3":"C.2.r.8"}'  WHERE MODULE_ID='ICSR' AND FIELD_ID='515012';

-- ── Table 520 — ICSR_SOURCE_INFORMATIONS ─────────────────────
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"A.2.2.1","r3":"C.3.1"}'   WHERE MODULE_ID='ICSR' AND FIELD_ID='520001';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"A.2.2.2","r3":"C.3.2"}'   WHERE MODULE_ID='ICSR' AND FIELD_ID='520002';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"A.2.2.3","r3":"C.3.3"}'   WHERE MODULE_ID='ICSR' AND FIELD_ID='520003';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"A.2.2.4","r3":"C.3.4"}'   WHERE MODULE_ID='ICSR' AND FIELD_ID='520004';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"A.2.2.5","r3":"C.3.5"}'   WHERE MODULE_ID='ICSR' AND FIELD_ID='520005';

-- ── Table 530 — ICSR_PATIENT ──────────────────────────────────
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.1","r3":"D.1"}'       WHERE MODULE_ID='ICSR' AND FIELD_ID='530001';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.2","r3":"D.5"}'       WHERE MODULE_ID='ICSR' AND FIELD_ID='530002';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"D.5.1"}'                  WHERE MODULE_ID='ICSR' AND FIELD_ID='530003';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.3","r3":"D.2.1"}'     WHERE MODULE_ID='ICSR' AND FIELD_ID='530004';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.4","r3":"D.2.2a"}'    WHERE MODULE_ID='ICSR' AND FIELD_ID='530005';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.4","r3":"D.2.2b"}'    WHERE MODULE_ID='ICSR' AND FIELD_ID='530006';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.5","r3":"D.2.3"}'     WHERE MODULE_ID='ICSR' AND FIELD_ID='530007';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.1.1","r3":"D.1.1"}'   WHERE MODULE_ID='ICSR' AND FIELD_ID='530009';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.6","r3":"D.3"}'       WHERE MODULE_ID='ICSR' AND FIELD_ID='530021';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.6","r3":"D.3"}'       WHERE MODULE_ID='ICSR' AND FIELD_ID='530022';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.7","r3":"D.4"}'       WHERE MODULE_ID='ICSR' AND FIELD_ID='530023';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.7","r3":"D.4"}'       WHERE MODULE_ID='ICSR' AND FIELD_ID='530024';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.8","r3":"D.6"}'       WHERE MODULE_ID='ICSR' AND FIELD_ID='530029';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.9","r3":"D.9"}'       WHERE MODULE_ID='ICSR' AND FIELD_ID='530030';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.10","r3":"D.10"}'     WHERE MODULE_ID='ICSR' AND FIELD_ID='530031';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.10","r3":"D.10"}'     WHERE MODULE_ID='ICSR' AND FIELD_ID='530032';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.11","r3":"D.7.1"}'    WHERE MODULE_ID='ICSR' AND FIELD_ID='530033';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.12","r3":"D.7.2"}'    WHERE MODULE_ID='ICSR' AND FIELD_ID='530034';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.13","r3":"D.11"}'     WHERE MODULE_ID='ICSR' AND FIELD_ID='530037';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.14","r3":"D.12"}'     WHERE MODULE_ID='ICSR' AND FIELD_ID='530038';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.1.2"}'                WHERE MODULE_ID='ICSR' AND FIELD_ID='530049';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"D.7"}'                    WHERE MODULE_ID='ICSR' AND FIELD_ID='530016';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"D.8"}'                    WHERE MODULE_ID='ICSR' AND FIELD_ID='530017';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"D.9.1"}'                  WHERE MODULE_ID='ICSR' AND FIELD_ID='530060';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"D.9.2"}'                  WHERE MODULE_ID='ICSR' AND FIELD_ID='530061';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"D.9.3"}'                  WHERE MODULE_ID='ICSR' AND FIELD_ID='530062';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"D.9.3"}'                  WHERE MODULE_ID='ICSR' AND FIELD_ID='530063';

-- ── Table 540 — ICSR_PATIENT_MEDICAL_HISTORIES ────────────────
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.11.1","r3":"D.7.1.r.1a"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='540001';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.11.1a","r3":"D.7.1.r.1b"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='540002';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"D.7.1.r.1c"}'                  WHERE MODULE_ID='ICSR' AND FIELD_ID='540003';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.11.2","r3":"D.7.1.r.2"}'   WHERE MODULE_ID='ICSR' AND FIELD_ID='540004';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.11.3","r3":"D.7.1.r.3"}'   WHERE MODULE_ID='ICSR' AND FIELD_ID='540005';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.11.4","r3":"D.7.1.r.4"}'   WHERE MODULE_ID='ICSR' AND FIELD_ID='540006';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"D.7.1.r.5"}'                   WHERE MODULE_ID='ICSR' AND FIELD_ID='540009';

-- ── Table 545 — ICSR_PATIENT_PAST_DRUG_THERAPIES ─────────────
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.12.1","r3":"D.8.r.1"}'  WHERE MODULE_ID='ICSR' AND FIELD_ID='545001';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.12.2","r3":"D.8.r.2"}'  WHERE MODULE_ID='ICSR' AND FIELD_ID='545002';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.12.3","r3":"D.8.r.3"}'  WHERE MODULE_ID='ICSR' AND FIELD_ID='545003';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.12.4","r3":"D.8.r.4"}'  WHERE MODULE_ID='ICSR' AND FIELD_ID='545004';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.12.5","r3":"D.8.r.5"}'  WHERE MODULE_ID='ICSR' AND FIELD_ID='545005';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"D.8.r.2.1a"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='545014';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"D.8.r.2.1b"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='545015';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"D.8.r.2.2a"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='545016';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"D.8.r.2.2b"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='545017';

-- ── Table 546 — ICSR_PAST_DRUG_SUBSTANCES ────────────────────
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"D.8.r.3.1"}'  WHERE MODULE_ID='ICSR' AND FIELD_ID='546001';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"D.8.r.3.2a"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='546002';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"D.8.r.3.2b"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='546003';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"D.8.r.3.3a"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='546004';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"D.8.r.3.3b"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='546005';

-- ── Table 550 — ICSR_PREGNANCY ────────────────────────────────
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"D.9.1"}'  WHERE MODULE_ID='ICSR' AND FIELD_ID='550001';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"D.9.2"}'  WHERE MODULE_ID='ICSR' AND FIELD_ID='550002';

-- ── Table 552 — ICSR_PREGNANCY_OUTCOMES ──────────────────────
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"D.9.3"}'  WHERE MODULE_ID='ICSR' AND FIELD_ID='552001';

-- ── Table 555 — ICSR_NEONATES ─────────────────────────────────
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"D.9.4"}'  WHERE MODULE_ID='ICSR' AND FIELD_ID='555001';

-- ── Table 560 — ICSR_DEATH_CAUSES ────────────────────────────
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.9.1","r3":"D.9.1.r"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='560102';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.9","r3":"D.9.1.r"}'   WHERE MODULE_ID='ICSR' AND FIELD_ID='560104';

-- ── Table 561 — ICSR_PATIENT_AUTOPSIES ───────────────────────
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.9.2","r3":"D.9.2.r"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='561002';

-- ── Table 565 — ICSR_PARENT ───────────────────────────────────
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.15"}'       WHERE MODULE_ID='ICSR' AND FIELD_ID='565013';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.15.1"}'     WHERE MODULE_ID='ICSR' AND FIELD_ID='565010';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.15.2"}'     WHERE MODULE_ID='ICSR' AND FIELD_ID='565009';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.15.3"}'     WHERE MODULE_ID='ICSR' AND FIELD_ID='565005';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.15.3"}'     WHERE MODULE_ID='ICSR' AND FIELD_ID='565008';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.15.4"}'     WHERE MODULE_ID='ICSR' AND FIELD_ID='565004';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.15.5"}'     WHERE MODULE_ID='ICSR' AND FIELD_ID='565015';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.15.5"}'     WHERE MODULE_ID='ICSR' AND FIELD_ID='565016';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.15.6"}'     WHERE MODULE_ID='ICSR' AND FIELD_ID='565011';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.15.6"}'     WHERE MODULE_ID='ICSR' AND FIELD_ID='565012';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.15.7"}'     WHERE MODULE_ID='ICSR' AND FIELD_ID='565014';

-- ── Table 570 — ICSR_PARENT_PAST_DRUG_THERAPIES ──────────────
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.15.8.1"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='570019';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.15.8.2"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='570022';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.15.8.3"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='570003';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.15.8.4"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='570005';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.15.8.5"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='570020';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"G.k.2.1.1"}'  WHERE MODULE_ID='ICSR' AND FIELD_ID='570014';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"G.k.2.1.2"}'  WHERE MODULE_ID='ICSR' AND FIELD_ID='570015';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"G.k.2.2.1"}'  WHERE MODULE_ID='ICSR' AND FIELD_ID='570016';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"G.k.2.2.2"}'  WHERE MODULE_ID='ICSR' AND FIELD_ID='570017';

-- ── Table 571 — ICSR_PARENT_PAST_DRUG_SUBSTANCES ─────────────
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"G.k.2.3.1"}'  WHERE MODULE_ID='ICSR' AND FIELD_ID='571003';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"G.k.2.3.2a"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='571005';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"G.k.2.3.2b"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='571004';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"G.k.2.3.3a"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='571001';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"G.k.2.3.3b"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='571002';

-- ── Table 575 — ICSR_PARENT_MED_HISTORIES ────────────────────
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.15.9.1"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='575010';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.1.15.9.2"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='575011';

-- ── Table 580 — ICSR_STUDY ────────────────────────────────────
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"C.5.1","r3":"G.k.1"}'    WHERE MODULE_ID='ICSR' AND FIELD_ID='580026';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"C.5.2","r3":"G.k.2"}'    WHERE MODULE_ID='ICSR' AND FIELD_ID='580034';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"C.5.3","r3":"G.k.3"}'    WHERE MODULE_ID='ICSR' AND FIELD_ID='580038';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"C.5.4","r3":"G.k.4"}'    WHERE MODULE_ID='ICSR' AND FIELD_ID='580030';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"C.5.5","r3":"G.k.5"}'    WHERE MODULE_ID='ICSR' AND FIELD_ID='580035';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"C.5.6","r3":"G.k.6"}'    WHERE MODULE_ID='ICSR' AND FIELD_ID='580001';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"C.5.7","r3":"G.k.7"}'    WHERE MODULE_ID='ICSR' AND FIELD_ID='580039';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"C.5.8","r3":"G.k.8"}'    WHERE MODULE_ID='ICSR' AND FIELD_ID='580023';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"C.5.9","r3":"G.k.9"}'    WHERE MODULE_ID='ICSR' AND FIELD_ID='580004';

-- ── Table 582 — ICSR_STUDY_REGISTRATIONS ─────────────────────
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"C.5.10.1","r3":"G.k.10.1"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='582004';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"C.5.10.2","r3":"G.k.10.2"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='582003';

-- ── Table 583 — ICSR_STUDY_CROSS_REF_INDS ────────────────────
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"C.5.11.1","r3":"G.k.11.1"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='583001';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"C.5.11.2"}'                  WHERE MODULE_ID='ICSR' AND FIELD_ID='583002';

-- ── Table 600 — ICSR_EVENT_REACTIONS ─────────────────────────
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.2.1","r3":"E.i.1"}'     WHERE MODULE_ID='ICSR' AND FIELD_ID='600029';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.2.1a","r3":"E.i.1a"}'   WHERE MODULE_ID='ICSR' AND FIELD_ID='600015';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"E.i.1b"}'                  WHERE MODULE_ID='ICSR' AND FIELD_ID='600016';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.2.2","r3":"E.i.2"}'     WHERE MODULE_ID='ICSR' AND FIELD_ID='600032';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"E.i.1.2"}'                 WHERE MODULE_ID='ICSR' AND FIELD_ID='600030';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"E.i.1.2a"}'                WHERE MODULE_ID='ICSR' AND FIELD_ID='600023';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.2.3","r3":"E.i.3"}'     WHERE MODULE_ID='ICSR' AND FIELD_ID='600024';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.2.4","r3":"E.i.4"}'     WHERE MODULE_ID='ICSR' AND FIELD_ID='600008';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.2.5","r3":"E.i.5"}'     WHERE MODULE_ID='ICSR' AND FIELD_ID='600013';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.2.5","r3":"E.i.5"}'     WHERE MODULE_ID='ICSR' AND FIELD_ID='600014';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"E.i.6a"}'                  WHERE MODULE_ID='ICSR' AND FIELD_ID='600046';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"E.i.6a"}'                  WHERE MODULE_ID='ICSR' AND FIELD_ID='600047';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"E.i.6b"}'                  WHERE MODULE_ID='ICSR' AND FIELD_ID='600044';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"E.i.6b"}'                  WHERE MODULE_ID='ICSR' AND FIELD_ID='600045';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.2.7","r3":"E.i.7"}'     WHERE MODULE_ID='ICSR' AND FIELD_ID='600026';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.2.6","r3":"E.i.6"}'     WHERE MODULE_ID='ICSR' AND FIELD_ID='600043';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.2.6.1","r3":"E.i.6.1"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='600035';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.2.6.2","r3":"E.i.6.2"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='600039';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.2.6.3","r3":"E.i.6.3"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='600033';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.2.6.4","r3":"E.i.6.4"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='600036';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.2.6.5","r3":"E.i.6.5"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='600034';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.2.6.6","r3":"E.i.6.6"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='600040';

-- ── Table 610 — ICSR_DRUG_PRODUCTS ───────────────────────────
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.4.k.2.1","r3":"G.k.2.2"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='610052';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"G.k.2.1.1"}'                 WHERE MODULE_ID='ICSR' AND FIELD_ID='610033';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"G.k.2.1.2"}'                 WHERE MODULE_ID='ICSR' AND FIELD_ID='610036';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"G.k.2.2.1"}'                 WHERE MODULE_ID='ICSR' AND FIELD_ID='610040';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"G.k.2.2.2"}'                 WHERE MODULE_ID='ICSR' AND FIELD_ID='610041';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.4.k.1","r3":"G.k.1"}'     WHERE MODULE_ID='ICSR' AND FIELD_ID='610050';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.4.k.6a","r3":"G.k.4.4"}'  WHERE MODULE_ID='ICSR' AND FIELD_ID='610011';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.4.k.6b","r3":"G.k.4.4"}'  WHERE MODULE_ID='ICSR' AND FIELD_ID='610012';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.4.k.15","r3":"G.k.9.i.3"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='610017';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.4.k.16","r3":"G.k.9.i.4"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='610018';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.4.k.7","r3":"G.k.8"}'     WHERE MODULE_ID='ICSR' AND FIELD_ID='610001';

-- ── Table 612 — ICSR_DRUG_ACTIVE_SUBSTANCES ───────────────────
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"G.k.2.3.1"}'  WHERE MODULE_ID='ICSR' AND FIELD_ID='612003';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"G.k.2.3.2a"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='612009';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"G.k.2.3.2b"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='612008';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"G.k.2.3.3a"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='612006';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"G.k.2.3.3b"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='612007';

-- ── Table 615 — ICSR_DRUG_THERAPIES ──────────────────────────
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.4.k.3","r3":"G.k.4.1"}'   WHERE MODULE_ID='ICSR' AND FIELD_ID='615031';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.4.k.4","r3":"G.k.4.2"}'   WHERE MODULE_ID='ICSR' AND FIELD_ID='615027';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.4.k.5","r3":"G.k.4.3"}'   WHERE MODULE_ID='ICSR' AND FIELD_ID='615007';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.4.k.5","r3":"G.k.4.3"}'   WHERE MODULE_ID='ICSR' AND FIELD_ID='615008';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.4.k.6a","r3":"G.k.4.4"}'  WHERE MODULE_ID='ICSR' AND FIELD_ID='615035';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.4.k.6b","r3":"G.k.4.4"}'  WHERE MODULE_ID='ICSR' AND FIELD_ID='615036';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.4.k.8","r3":"G.k.4.6"}'   WHERE MODULE_ID='ICSR' AND FIELD_ID='615012';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.4.k.9","r3":"G.k.4.7"}'   WHERE MODULE_ID='ICSR' AND FIELD_ID='615013';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.4.k.9","r3":"G.k.4.7"}'   WHERE MODULE_ID='ICSR' AND FIELD_ID='615014';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.4.k.10","r3":"G.k.4.8"}'  WHERE MODULE_ID='ICSR' AND FIELD_ID='615023';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"G.k.4.8.1"}'                 WHERE MODULE_ID='ICSR' AND FIELD_ID='615025';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"G.k.4.8.2"}'                 WHERE MODULE_ID='ICSR' AND FIELD_ID='615024';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.4.k.11","r3":"G.k.4.9"}'  WHERE MODULE_ID='ICSR' AND FIELD_ID='615009';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"G.k.4.9.1"}'                 WHERE MODULE_ID='ICSR' AND FIELD_ID='615022';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"G.k.4.9.2"}'                 WHERE MODULE_ID='ICSR' AND FIELD_ID='615021';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.4.k.12","r3":"G.k.4.10"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='615017';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.4.k.13","r3":"G.k.4.11"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='615016';

-- ── Table 620 — ICSR_DRUG_INDICATIONS ────────────────────────
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.4.k.11","r3":"G.k.7.1"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='620001';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.4.k.11a"}'                WHERE MODULE_ID='ICSR' AND FIELD_ID='620002';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"G.k.7.2"}'                  WHERE MODULE_ID='ICSR' AND FIELD_ID='620003';

-- ── Table 630 — ICSR_DRUG_APPROVALS ──────────────────────────
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.4.k.2.2","r3":"G.k.3.1"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='630006';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.4.k.2.2","r3":"G.k.3.2"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='630004';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.4.k.2.2","r3":"G.k.3.3"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='630005';

-- ── Table 635 — ICSR_DRUG_REACTION_RELATEDNESS ───────────────
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.4.k.7","r3":"G.k.8"}'      WHERE MODULE_ID='ICSR' AND FIELD_ID='635005';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.4.k.15","r3":"G.k.9.i.3"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='635010';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.4.k.16","r3":"G.k.9.i.4"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='635017';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.4.k.17","r3":"G.k.9.i.1"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='635008';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.4.k.18","r3":"G.k.9.i.2"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='635019';

-- ── Table 636 — ICSR_DRUG_REACTION_LABELLINGS ────────────────
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.4.k.17.1","r3":"G.k.9.i.1"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='636002';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.4.k.17.1","r3":"G.k.9.i.1"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='636003';

-- ── Table 640 — ICSR_LAB_TESTS ────────────────────────────────
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.3.1.a","r3":"F.r.1"}'   WHERE MODULE_ID='ICSR' AND FIELD_ID='640009';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.3.1.a","r3":"F.r.1a"}'  WHERE MODULE_ID='ICSR' AND FIELD_ID='640010';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"F.r.1b"}'                  WHERE MODULE_ID='ICSR' AND FIELD_ID='640011';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.3.1.b","r3":"F.r.2"}'   WHERE MODULE_ID='ICSR' AND FIELD_ID='640008';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.3.1.c","r3":"F.r.3"}'   WHERE MODULE_ID='ICSR' AND FIELD_ID='640013';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.3.1.d","r3":"F.r.3.1"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='640012';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.3.1.e","r3":"F.r.3.2"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='640014';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.3.1.f","r3":"F.r.4"}'   WHERE MODULE_ID='ICSR' AND FIELD_ID='640007';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.3.1.g","r3":"F.r.5.1"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='640006';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"B.3.1.h","r3":"F.r.5.2"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='640005';

-- ── Table 645 — ICSR_LITERATURE ───────────────────────────────
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r2":"A.2.3.1","r3":"C.4.r.1"}' WHERE MODULE_ID='ICSR' AND FIELD_ID='645009';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"C.4.r.2"}'                 WHERE MODULE_ID='ICSR' AND FIELD_ID='645002';
UPDATE TABLE_COLUMN_METADATA SET LABEL_INFO = '{"r3":"C.4.r.3"}'                 WHERE MODULE_ID='ICSR' AND FIELD_ID='645003';
